version: '3.8'

services:
  default:
    build: .
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ./lab.ovpn:/workdir/lab.ovpn
    tty: true
    stdin_open: true 